### ISSUE TITLE
JasminSMS as vendor

### ISSUE THREAD

**Issue by globalgen** [DoubleBastionAdmin/sms-relentless#3]
Dear DEVs

Your kind advise on how to add a setting for JasminSMS is greatly appreciated. API POST format is
DOCS: https://docs.jasminsms.com/en/latest/apis/rest/index.html#

Example from DOCs sending message:

curl -X POST -H 'Authorization: Basic  Zm9vOmJhcg==' -d '{"to":phonenumber,"from":"alphanumeric","content":"sms content"}'  http://yourdomain:8080/secure/send 

Example from DOCs of sending same message to multiple destinations:

curl -X POST -H 'Authorization: Basic Zm9vOmJhcg==' -d '{
  "messages": [
    {
      "to": [
        "33333331",
        "33333332",
        "33333333"
      ],
      "content": "Same content goes to 3 numbers"
    }
  ]
}' http://yourdomain:8080/secure/sendbatch

**Comment by DoubleBastionAdmin** [comment]
SMS Relentless wasn't built to interact with an SMS Gateway like 'Jasmin Gateway'. The app can be connected only directly to these 4 providers: Telnyx, Plivo, Twilio, Flowroute. Once the user has his Telnyx/Plivo/Twilio/Flowroute account and a phone number rented from that provider, he can copy the API credentials from the SMS provider on the Settings page of the app and this is it: the connection is established. He can send and receive SMS messages using the number(s) rented from Telnyx or Plivo or Twilio or Flowroute. A message can be sent even to multiple destinations at once. There is no need to proxy the messages through a gateway like Jasmin Gateway, which is not an SMS provider or vendor, but a gateway which functions like a proxy for SMS traffic.
